### PR TITLE
Localizations added

### PR DESCRIPTION
**Pull request by PJ7536**
# This PR consolidates the following:
- added a string file instance using which we can add and apply Localizations
- please go through and suggest changes if needed

### CODE REVIEW

**Comment by PJ7536** [comment]
@tneotia can you please take a look at this

**Comment by tneotia** [comment]
Please remove idea directory, thanks :)

I also don't think all the strings got translated in this, for example choose a color is not.

**Comment by Romavic** [comment]
@tneotia all string must be translated yes, its is very needed.

@PJ7536 good pr

**Review by Romavic — APPROVED** [review]

**Comment by PJ7536** [comment]
@tneotia can you please take a look at this added the remaining strings and deleted .idea directory

**Pull request closed without merging**
