### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by ksilz**
I updated these three dependencies: `pointer_interceptor`, `file_picker`, and `flutter_keyboard_visibility`. See #295.

### CODE REVIEW

**Review by kostas95 — APPROVED** [review]

**Review by lucasdidur — APPROVED** [review]

**Comment by mkiisoft** [comment]
Can we get this approved?

**Comment by TejaChirala** [comment]
Can we get this merged?

**Review by ES-fooshen — APPROVED** [review]
LGTM, can reviewer approve and merge this

**Comment by ksilz** [comment]
@lucasdidur @kostas95 @ES-fooshen What do I need to do to move this PR forward? It's missing an "approving review by reviewers with write access".

**Comment by tneotia** [comment]
I don't have time to test unfortunately, but I'm going to go ahead and merge and hope these don't break the plugin. Thanks for the PR :)

**Review by tneotia — APPROVED** [review]

**Pull request merged**
