### PR TITLE
Upgrade flutter_colorpicker

### PR DESCRIPTION
**Pull request by eliudio**
flutter_colorpicker: ^0.6.0

### CODE REVIEW

**Review by tneotia — APPROVED** [review]
LGTM except I am going to hold off merging this for a bit - if I merge and release this it will require me to bump minimum Flutter version to 2.5.0, which just recently came out. As a result I am going to wait a couple more weeks before this breaking change in case people have put off upgrading to latest stable.

**Comment by eliudio** [comment]
Ok. I understand.I had to do this because the upgrade to flutter 2.5: basically currently html-editor-enhanced does not work with flutter 2.5 This is because of the old version of flutter_colorpicker is not compatible with flutter 2.5Keep up the good work.ThanksOn 19 Sep 2021 20:56, Tanay Neotia ***@***.***> wrote:
@tneotia approved this pull request.

LGTM except I am going to hold off merging this for a bit - if I merge and release this it will require me to bump minimum Flutter version to 2.5.0, which just recently came out. As a result I am going to wait a couple more weeks before this breaking change in case people have put off upgrading to latest stable.

**Comment by tneotia** [comment]
See #137, you can fix the issue without any modifications to the package in case you are interested in doing that.

**Comment by eliudio** [comment]
That's cool. I learned. ThanksOn 20 Sep 2021 02:29, Tanay Neotia ***@***.***> wrote:
See #137, you can fix the issue without any modifications to the package in case you are interested in doing that.

**Comment by ukieTux** [comment]
When you will update using this MR @tneotia  ?

Thanks

**Comment by tneotia** [comment]
> When you will update using this MR @tneotia ?

I am working to push an update to the package this weekend, actually I am removing this dependency entirely. Due to #148 the current color picker package does not work that well so I need to swap it out.

**Pull request merged**
