### PR TITLE
Bug fix for "No file or variants found for asset: ..."

### PR DESCRIPTION
**Pull request by kimmanwky**
Bug fix for "No file or variants found for asset: packages/html_editor_enhanced/summernote.html"

Bug Fix for:
#341 #331

### CODE REVIEW

**Comment by noobcoder95** [comment]
hello, why does'nt anyone merge this PR? many of us still facing the issue and cannot continue our project

**Review by IFLyer — APPROVED** [review]

**Review by IFLyer — APPROVED** [review]

**Review by noobcoder95 — APPROVED** [review]

**Comment by sunflash** [comment]
@tneotia  Please merge the fix for assets and send out a new release.  Can't build my app at all with recent release of flutter 3.7.0

**Review by tneotia — APPROVED** [review]
LGTM

**Comment by tneotia** [comment]
Sorry guys, been very busy with other projects. Only have time to look at critical issues or bug fixes for this package these days - if this is breaking I will merge and publish new version.

**Comment by sunflash** [comment]
@tneotia Thanks, it works again.

**Pull request merged**
